// <auto-generated />
using System;
using Interview_Test.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Interview_Test.Infrastructure.Migrations
{
    [DbContext(typeof(InterviewTestDbContext))]
    [Migration("20251212142915_InitializeDb")]
    partial class InitializeDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Interview_Test.Models.PermissionModel", b =>
                {
                    b.Property<long>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PermissionId"));

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("PermissionTb");

                    b.HasData(
                        new
                        {
                            PermissionId = 1L,
                            Permission = "1-01-picking-info",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 2L,
                            Permission = "1-02-picking-start",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 3L,
                            Permission = "1-03-picking-confirm",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 4L,
                            Permission = "1-04-picking-report",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 5L,
                            Permission = "2-01-packing-info",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 6L,
                            Permission = "2-02-packing-start",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 7L,
                            Permission = "2-03-packing-confirm",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 8L,
                            Permission = "2-04-packing-report",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 9L,
                            Permission = "3-01-printing-label",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Interview_Test.Models.RoleModel", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("RoleId");

                    b.ToTable("RoleTb");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "pick operation"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "pack operation"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "document operation"
                        });
                });

            modelBuilder.Entity("Interview_Test.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserTb");
                });

            modelBuilder.Entity("Interview_Test.Models.UserProfileModel", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("ProfileId");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasFilter("[Id] IS NOT NULL");

                    b.ToTable("UserProfileTb");
                });

            modelBuilder.Entity("Interview_Test.Models.UserRoleMappingModel", b =>
                {
                    b.Property<Guid>("UserRoleMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserRoleMappingId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoleMappingTb");
                });

            modelBuilder.Entity("Interview_Test.Models.PermissionModel", b =>
                {
                    b.HasOne("Interview_Test.Models.RoleModel", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Interview_Test.Models.UserProfileModel", b =>
                {
                    b.HasOne("Interview_Test.Models.UserModel", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("Interview_Test.Models.UserProfileModel", "Id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Interview_Test.Models.UserRoleMappingModel", b =>
                {
                    b.HasOne("Interview_Test.Models.RoleModel", "Role")
                        .WithMany("UserRoleMappings")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interview_Test.Models.UserModel", "User")
                        .WithMany("UserRoleMappings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Interview_Test.Models.RoleModel", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserRoleMappings");
                });

            modelBuilder.Entity("Interview_Test.Models.UserModel", b =>
                {
                    b.Navigation("UserProfile")
                        .IsRequired();

                    b.Navigation("UserRoleMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
